export { AvatarScene } from './scene';
export { CameraController } from './camera-controller';
export type { CameraMode } from './camera-controller';
export { ExpressionController, sentimentToExpression } from './expressions';
export type { Expression } from './expressions';
export { LipSync } from './lip-sync';
export { IdleAnimation } from './idle-animation';
export type { IdleConfig } from './idle-animation';
export { GestureController } from './gestures';
export type { GestureType } from './gestures';
export { IdleVariationManager } from './idle-variations';
export type { IdleVariationType } from './idle-variations';
export { GazeController } from './gaze';
export type { GazeMode, DockHint } from './gaze';
export { BasePose } from './base-pose';
export { NonHumanoidAnimator } from './non-humanoid-animation';
export { MicroExpressionController } from './micro-expressions';
export { SurpriseAnimationController } from './surprise-animations';
